version: "3"
services:
  db:
    image: neo4j:4.4.7-enterprise
    container_name: db_testint
    ports:
      - "5087:7687"
      - "5074:7474"
      - "5073:7473"
    environment: 
      - NEO4J_AUTH=neo4j/changeme1234
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_trigger_enabled=true
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=500m
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:5087
      - NEO4J_dbms_connector_http_advertised__address=localhost:5074
      - NEO4J_dbms_connector_https_advertised__address=localhost:5073
      - NEO4J_metrics_jmx_enabled=true
      - NEO4JLABS_PLUGINS=["apoc"]
